# global
random_seed: 114514

data:
  # preprocess
  preprocess: true
  data_dir: data/
  sample_rate: 16000
  max_length: 50.0 # unit: seconds

  # vocab
  special_phones:
    - SP
    - AP
  ignored_phones:
    - pau
    - ''
  phone_aliases:
    SP:  # "<SP>", "<EOS>", "cl", and "sil" will be replaced by "SP"
      - <SP>
      - <EOS>
      - sil
      - cl
    AP: 
      - <AP>

  valid:
    size: 15
    preferred:
      - valid
      - test
  loader:
    batch_length: 100
    randomize_factor: 0.2
    num_workers: 16