[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "torchsofa"
version = "2.0.0"
dependencies = ["requests", 'importlib-metadata; python_version<"3.10"']
